"""Add validation metrics and feature importance to regression model

Revision ID: 11a88e82035f
Revises: b5d6ae97b2d4
Create Date: 2025-06-18 01:47:17.968706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11a88e82035f'
down_revision: Union[str, None] = 'b5d6ae97b2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regression_models', sa.Column('preprocessing_params', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    op.add_column('regression_models', sa.Column('validation_metrics', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    op.add_column('regression_models', sa.Column('feature_importance', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regression_models', 'feature_importance')
    op.drop_column('regression_models', 'validation_metrics')
    op.drop_column('regression_models', 'preprocessing_params')
    # ### end Alembic commands ###
