"""Added platform car model relation

Revision ID: 11c4824d2991
Revises: cbf75eeeaa87
Create Date: 2025-06-15 13:28:11.873076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11c4824d2991'
down_revision: Union[str, None] = 'cbf75eeeaa87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_model_platforms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('car_model_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.UUID(), nullable=False),
    sa.Column('platform_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_model_id'], ['car_models.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_model_platforms')
    # ### end Alembic commands ###
