"""Added possible_names to part_categories

Revision ID: b5d6ae97b2d4
Revises: 11c4824d2991
Create Date: 2025-06-16 19:57:07.743460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d6ae97b2d4'
down_revision: Union[str, None] = '11c4824d2991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part_categories', sa.Column('possible_names', sa.JSON(), nullable=False, server_default='[]'))
    op.create_index(op.f('ix_parts_oem_number'), 'parts', ['oem_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parts_oem_number'), table_name='parts')
    op.drop_column('part_categories', 'possible_names')
    # ### end Alembic commands ###
