"""Initial migration

Revision ID: cbf75eeeaa87
Revises: 
Create Date: 2025-06-15 02:42:43.653846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbf75eeeaa87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_brands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_origin', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_manufacturers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platforms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('search_url_template', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year_from', sa.DateTime(), nullable=False),
    sa.Column('year_to', sa.DateTime(), nullable=False),
    sa.Column('body_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['car_brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('oem_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('manufacturer_id', sa.UUID(), nullable=False),
    sa.Column('specifications', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['part_categories.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['part_manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regression_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_variable', sa.String(), nullable=False),
    sa.Column('feature_variables', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('coefficients', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('intercept', sa.Float(), nullable=False),
    sa.Column('r_squared', sa.Float(), nullable=False),
    sa.Column('mean_squared_error', sa.Float(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('last_trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('training_data_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['part_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_models',
    sa.Column('car_model_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['car_model_id'], ['car_models.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('car_model_id', 'part_id')
    )
    op.create_table('scraped_part_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title_on_platform', sa.String(), nullable=False),
    sa.Column('article_number', sa.String(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('availability_status', sa.String(), nullable=False),
    sa.Column('delivery_days', sa.Integer(), nullable=True),
    sa.Column('seller_name', sa.String(), nullable=False),
    sa.Column('seller_rating', sa.Float(), nullable=True),
    sa.Column('seller_type', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('warranty_months', sa.Integer(), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=True),
    sa.Column('search_position', sa.Integer(), nullable=False),
    sa.Column('images', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraped_part_data')
    op.drop_table('part_models')
    op.drop_table('regression_models')
    op.drop_table('parts')
    op.drop_table('car_models')
    op.drop_table('platforms')
    op.drop_table('part_manufacturers')
    op.drop_table('part_categories')
    op.drop_table('car_brands')
    # ### end Alembic commands ###
